--- 
abstract: Dist::Zilla like FAYLAND when you build your dists
author: 
  - Fayland Lam <fayland@gmail.com>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.091260
license: perl
name: Dist-Zilla-PluginBundle-FAYLAND
requires: 
  Dist::Zilla: 1.091370
  Dist::Zilla::Plugin::CheckChangeLog: 0.01
  Dist::Zilla::Plugin::PerlTidy: 0.04
  Dist::Zilla::Plugin::PodWeaver: 2.000
  Dist::Zilla::Plugin::ReadmeFromPod: 0.03
  Dist::Zilla::Plugin::Repository: 0.08
resources: 
  repository: http://github.com/fayland/dist-zilla-pluginbundle-fayland/tree
version: 0.01
