---
abstract: 'Dist::Zilla like FAYLAND when you build your dists'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-FAYLAND
requires:
  Dist::Zilla: 1.092990
  Dist::Zilla::Plugin::CheckChangeLog: 0.01
  Dist::Zilla::Plugin::CompileTests: 0.05
  Dist::Zilla::Plugin::PerlTidy: 0.06
  Dist::Zilla::Plugin::PodWeaver: 3.092971
  Dist::Zilla::Plugin::ReadmeFromPod: 0.03
  Dist::Zilla::Plugin::Repository: 0.08
resources:
  repository: git://github.com/fayland/dist-zilla-pluginbundle-fayland.git
version: 0.09
